language: php

php: 7.2

sudo: false

env:
  - APP_KEY=base64:xIqp823QoWI8aYcDVlMpLlhFDodhCIFpwh0VQe6CEtg=

cache:
  directories:
    - vendor

before_script:
  - composer install

script: vendor/bin/phpunit --verbose

deploy:
  provider: script
  script: curl ${ENVOYER_DEPLOYMENT_HOOK}?sha=${TRAVIS_COMMIT}
  on:
    branch: master
