language: php

php: 7.1

sudo: false

cache:
  directories:
    - vendor

before_script:
  - composer self-update
  - composer install

script: vendor/bin/phpunit

deploy:
  provider: script
  script: curl $ENVOYER_DEPLOYMENT_HOOK
  on:
    branch: master
