name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Install NPM dependencies
        run: npm ci

      - name: Compile assets
        run: npm run build

      - name: Execute tests
        run: vendor/bin/phpunit

  dependabot:
    needs: [tests]
    permissions:
      pull-requests: write
      contents: write
    uses: driesvints/github-workflows/.github/workflows/dependabot.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        if: github.repository == 'laravelio/paste.laravel.io' && github.ref_name == 'main'
        run: curl ${{ secrets.ENVOYER_HOOK }}?sha=${{ github.sha }}
